create table if not exists public.gallery_albums (
  id bigint generated by default as identity primary key,
  year integer not null,
  title varchar(180) not null,
  category varchar(120) not null,
  event_date varchar(80) not null,
  location varchar(120) not null,
  image_url text not null,
  image_alt varchar(255) not null,
  photo_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_posts (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  excerpt text not null,
  content text not null,
  category varchar(120) not null,
  published_at varchar(80) not null,
  image_url text not null default '',
  status varchar(20) not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.board_members (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  role varchar(160) not null,
  bio text not null,
  image_url text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  name varchar(160) not null,
  email varchar(320) not null unique,
  role varchar(40) not null default 'admin' check (role in ('admin', 'editor', 'board_manager')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.gallery_albums enable row level security;
alter table public.news_posts enable row level security;
alter table public.board_members enable row level security;
alter table public.admin_users enable row level security;

create policy "Public can read gallery albums" on public.gallery_albums for select to anon, authenticated using (true);
create policy "Public can read published news" on public.news_posts for select to anon, authenticated using (status = 'published');
create policy "Public can read active board members" on public.board_members for select to anon, authenticated using (active = true);
create policy "Admins can manage gallery" on public.gallery_albums for all to authenticated using (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active)) with check (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active));
create policy "Admins can manage news" on public.news_posts for all to authenticated using (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active)) with check (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active));
create policy "Admins can manage board" on public.board_members for all to authenticated using (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active)) with check (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active));
create policy "Admins can read admin users" on public.admin_users for select to authenticated using (exists (select 1 from public.admin_users a where (a.user_id = auth.uid() or lower(a.email) = lower(auth.jwt() ->> 'email')) and a.active));

insert into storage.buckets (id, name, public) values ('cestom-media', 'cestom-media', true) on conflict (id) do nothing;
create policy "Public can view CESTOM media" on storage.objects for select to public using (bucket_id = 'cestom-media');
create policy "Admins can upload CESTOM media" on storage.objects for insert to authenticated with check (bucket_id = 'cestom-media');
