import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import ImageUploader from "@/components/admin/ImageUploader";
import { trpc } from "@/lib/trpc";
import { Link, useLocation } from "wouter";
import { BarChart3, CheckCircle2, ExternalLink, Images, LayoutDashboard, Newspaper, Pencil, Plus, Save, ShieldCheck, Trash2, Users, X } from "lucide-react";

type GalleryPhotoForm = { url: string; alt: string };
type GalleryForm = { year: string; title: string; category: string; eventDate: string; location: string; imageAlt: string; photos: GalleryPhotoForm[] };
type NewsForm = { title: string; excerpt: string; content: string; category: string; publishedAt: string; imageUrl: string; status: "draft" | "published" };
type BoardForm = { name: string; role: string; bio: string; imageUrl: string; sortOrder: string; active: boolean };
const emptyGallery: GalleryForm = { year: "2025", title: "", category: "Vie communautaire", eventDate: "", location: "Marrakech", imageAlt: "", photos: [] };
const emptyNews: NewsForm = { title: "", excerpt: "", content: "", category: "Vie de la communauté", publishedAt: new Date().toISOString().slice(0, 10), imageUrl: "", status: "draft" };
const emptyBoard: BoardForm = { name: "", role: "", bio: "", imageUrl: "", sortOrder: "0", active: true };

export default function Admin() { return <DashboardLayout><AdminContent /></DashboardLayout>; }
function AdminContent() {
  const { user } = useAuth();
  const [location] = useLocation();
  if (user?.role !== "admin") return <div className="flex min-h-[70vh] items-center justify-center"><div className="max-w-md rounded-[1.5rem] border border-[#e1e9e2] bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto size-10 text-[#d62828]" /><h1 className="mt-5 text-2xl font-extrabold">Accès administrateur requis</h1><p className="mt-3 text-sm leading-6 text-[#74877b]">Votre compte doit posséder le rôle administrateur pour gérer le contenu.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#075b36] px-5 py-3 text-sm font-extrabold text-white">Retour au site <ExternalLink className="size-4" /></Link></div></div>;
  const section = location === "/admin/actualites" ? "news" : location === "/admin/bureau" ? "board" : "gallery";
  return <div className="min-h-screen bg-[#f7faf7] text-[#17221c]"><div className="mb-8 border-b border-[#e1e9e2] pb-7"><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.18em] text-[#009b3a]"><LayoutDashboard className="size-4" /> Espace de gestion</div><h1 className="mt-3 text-4xl font-black tracking-[-0.06em] text-[#075b36] sm:text-5xl">Bonjour {user?.name?.split(" ")[0] || "administrateur"}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#74877b]">Gérez les contenus publics de la Coordination des étudiants et stagiaires togolais au Maroc — Section Marrakech depuis un seul espace.</p></div>{section === "gallery" ? <GalleryAdmin /> : section === "news" ? <NewsAdmin /> : <BoardAdmin />}</div>;
}

function GalleryAdmin() {
  const [form, setForm] = useState(emptyGallery);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const query = trpc.gallery.list.useQuery();
  const create = trpc.gallery.create.useMutation({ onSuccess: () => success("Album ajouté."), onError: (error) => setNotice(`Erreur : ${error.message}`) });
  const update = trpc.gallery.update.useMutation({ onSuccess: () => success("Album mis à jour."), onError: (error) => setNotice(`Erreur : ${error.message}`) });
  const remove = trpc.gallery.remove.useMutation({ onSuccess: () => { setNotice("Album supprimé."); void utils.gallery.list.invalidate(); }, onError: (error) => setNotice(`Erreur : ${error.message}`) });
  const albums = query.data ?? [];
  const totalPhotos = useMemo(() => albums.reduce((sum, album) => sum + album.photoCount, 0), [albums]);

  function success(message: string) { setNotice(message); setEditingId(null); setForm(emptyGallery); void utils.gallery.list.invalidate(); }
  function submit(event: React.FormEvent) {
    event.preventDefault();
    if (form.photos.length === 0) { setNotice("Ajoutez au moins une photo à l’album."); return; }
    if (form.imageAlt.trim().length < 2) { setNotice("Ajoutez un texte alternatif d’au moins 2 caractères."); return; }
    const payload = { year: Number(form.year), title: form.title, category: form.category, eventDate: form.eventDate, location: form.location, photos: form.photos.map((photo) => ({ imageUrl: photo.url, imageAlt: form.imageAlt })) };
    editingId ? update.mutate({ id: editingId, ...payload }) : create.mutate(payload);
  }
  function editAlbum(album: (typeof albums)[number]) {
    setEditingId(album.id);
    setForm({ year: String(album.year), title: album.title, category: album.category, eventDate: album.eventDate, location: album.location, imageAlt: album.imageAlt, photos: album.photos?.map((photo) => ({ url: photo.imageUrl, alt: photo.imageAlt })) ?? [{ url: album.imageUrl, alt: album.imageAlt }] });
  }
  return <AdminSection title="Galerie" eyebrow="Mémoire en images" icon={<Images className="size-5" />} stats={<><AdminStat value={albums.length} label="albums" icon={<Images className="size-5" />} /><AdminStat value={new Set(albums.map((a) => a.year)).size} label="années" icon={<BarChart3 className="size-5" />} /><AdminStat value={totalPhotos} label="photos référencées" icon={<CheckCircle2 className="size-5" />} /></>}><div className="grid gap-8 xl:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)]"><Panel title={editingId ? "Modifier un album" : "Ajouter un album"}><form className="space-y-4" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Année" type="number" value={form.year} onChange={(v) => setForm({ ...form, year: v })} required /><div className="rounded-xl border border-[#dfe8e0] bg-[#f7faf7] px-4 py-3 text-sm"><span className="block text-xs font-extrabold uppercase tracking-[0.1em] text-[#587063]">Photos sélectionnées</span><strong className="mt-1 block text-xl text-[#075b36]">{form.photos.length}</strong></div></div><Field label="Nom de l’événement" value={form.title} onChange={(v) => setForm({ ...form, title: v })} required /><div className="grid gap-4 sm:grid-cols-2"><Field label="Catégorie" value={form.category} onChange={(v) => setForm({ ...form, category: v })} required /><Field label="Date affichée" value={form.eventDate} onChange={(v) => setForm({ ...form, eventDate: v })} required /></div><Field label="Lieu" value={form.location} onChange={(v) => setForm({ ...form, location: v })} required /><ImageUploader values={form.photos.map((photo) => photo.url)} onChange={(urls) => setForm({ ...form, photos: urls.map((url, index) => ({ url, alt: form.photos[index]?.alt ?? form.imageAlt })) })} label="Photos de l’album" multiple required /><Field label="Texte alternatif commun" value={form.imageAlt} onChange={(v) => setForm({ ...form, imageAlt: v })} placeholder="Photos de l’événement CESTOM" required /><Actions notice={notice} onCancel={editingId ? () => { setEditingId(null); setForm(emptyGallery); } : undefined} saving={create.isPending || update.isPending} label={editingId ? "Enregistrer" : "Ajouter l’album"} /></form></Panel><ContentList title="Albums actuels" loading={query.isLoading} empty="Aucun album créé"><div className="space-y-3">{albums.map((album) => <ListRow key={album.id} image={album.imageUrl} title={album.title} meta={`${album.year} · ${album.photoCount} photo${album.photoCount > 1 ? "s" : ""}`} onEdit={() => editAlbum(album)} onDelete={() => window.confirm(`Supprimer « ${album.title} » ?`) && remove.mutate({ id: album.id })} />)}</div></ContentList></div></AdminSection>;
}
function NewsAdmin() {
  const [form, setForm] = useState(emptyNews); const [editingId, setEditingId] = useState<number | null>(null); const [notice, setNotice] = useState<string | null>(null); const utils = trpc.useUtils(); const query = trpc.news.adminList.useQuery(); const create = trpc.news.create.useMutation({ onSuccess: () => success("Publication enregistrée."), onError: (error) => setNotice(`Erreur : ${error.message}`) }); const update = trpc.news.update.useMutation({ onSuccess: () => success("Publication mise à jour."), onError: (error) => setNotice(`Erreur : ${error.message}`) }); const remove = trpc.news.remove.useMutation({ onSuccess: () => { setNotice("Publication supprimée."); void utils.news.adminList.invalidate(); }, onError: (error) => setNotice(`Erreur : ${error.message}`) }); const posts = query.data ?? [];
  function success(message: string) { setNotice(message); setEditingId(null); setForm(emptyNews); void utils.news.adminList.invalidate(); }
  function submit(event: React.FormEvent) { event.preventDefault(); const payload = { ...form }; editingId ? update.mutate({ id: editingId, ...payload }) : create.mutate(payload); }
  return <AdminSection title="Actualités" eyebrow="Publications" icon={<Newspaper className="size-5" />}><div className="grid gap-8 xl:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)]"><Panel title={editingId ? "Modifier la publication" : "Nouvelle publication"}><form className="space-y-4" onSubmit={submit}><Field label="Titre" value={form.title} onChange={(v) => setForm({ ...form, title: v })} required /><Field label="Catégorie" value={form.category} onChange={(v) => setForm({ ...form, category: v })} required /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date de publication" type="date" value={form.publishedAt} onChange={(v) => setForm({ ...form, publishedAt: v })} required /><label className="block text-sm font-bold"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-[#587063]">Statut</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as NewsForm["status"] })} className="h-11 w-full rounded-xl border border-[#dfe8e0] bg-white px-3.5 text-sm"><option value="draft">Brouillon</option><option value="published">Publié</option></select></label></div><Field label="Résumé" value={form.excerpt} onChange={(v) => setForm({ ...form, excerpt: v })} required /><label className="block text-sm font-bold"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-[#587063]">Contenu</span><textarea value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} required rows={8} className="w-full rounded-xl border border-[#dfe8e0] bg-white px-3.5 py-3 text-sm" /></label><ImageUploader value={form.imageUrl} onChange={(v) => setForm({ ...form, imageUrl: v })} label="Image de couverture" /><Actions notice={notice} onCancel={editingId ? () => { setEditingId(null); setForm(emptyNews); } : undefined} saving={create.isPending || update.isPending} label={editingId ? "Enregistrer" : "Publier / enregistrer"} /></form></Panel><ContentList title="Publications" loading={query.isLoading} empty="Aucune publication"><div className="space-y-3">{posts.map((post) => <ListRow key={post.id} image={post.imageUrl} title={post.title} meta={`${post.status === "published" ? "Publié" : "Brouillon"} · ${post.publishedAt}`} onEdit={() => { setEditingId(post.id); setForm({ title: post.title, excerpt: post.excerpt, content: post.content, category: post.category, publishedAt: post.publishedAt, imageUrl: post.imageUrl, status: post.status }); }} onDelete={() => window.confirm(`Supprimer « ${post.title} » ?`) && remove.mutate({ id: post.id })} />)}</div></ContentList></div></AdminSection>;
}

function BoardAdmin() {
  const [form, setForm] = useState(emptyBoard); const [editingId, setEditingId] = useState<number | null>(null); const [notice, setNotice] = useState<string | null>(null); const utils = trpc.useUtils(); const query = trpc.board.adminList.useQuery(); const create = trpc.board.create.useMutation({ onSuccess: () => success("Membre ajouté."), onError: (error) => setNotice(`Erreur : ${error.message}`) }); const update = trpc.board.update.useMutation({ onSuccess: () => success("Membre mis à jour."), onError: (error) => setNotice(`Erreur : ${error.message}`) }); const remove = trpc.board.remove.useMutation({ onSuccess: () => { setNotice("Membre supprimé."); void utils.board.adminList.invalidate(); }, onError: (error) => setNotice(`Erreur : ${error.message}`) }); const members = query.data ?? [];
  function success(message: string) { setNotice(message); setEditingId(null); setForm(emptyBoard); void utils.board.adminList.invalidate(); }
  function submit(event: React.FormEvent) { event.preventDefault(); const payload = { name: form.name, role: form.role, bio: form.bio, imageUrl: form.imageUrl, sortOrder: Number(form.sortOrder), active: form.active ? 1 : 0 }; editingId ? update.mutate({ id: editingId, ...payload }) : create.mutate(payload); }
  return <AdminSection title="Bureau exécutif" eyebrow="Équipe dirigeante" icon={<Users className="size-5" />}><div className="grid gap-8 xl:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)]"><Panel title={editingId ? "Modifier un membre" : "Ajouter un membre"}><form className="space-y-4" onSubmit={submit}><Field label="Nom complet" value={form.name} onChange={(v) => setForm({ ...form, name: v })} required /><Field label="Fonction" value={form.role} onChange={(v) => setForm({ ...form, role: v })} placeholder="Président(e)" required /><label className="block text-sm font-bold"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-[#587063]">Biographie</span><textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} required rows={6} className="w-full rounded-xl border border-[#dfe8e0] bg-white px-3.5 py-3 text-sm" /></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Ordre d’affichage" type="number" value={form.sortOrder} onChange={(v) => setForm({ ...form, sortOrder: v })} required /><label className="flex items-center gap-3 pt-6 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} className="size-4 accent-[#075b36]" /> Afficher sur le site</label></div><ImageUploader value={form.imageUrl} onChange={(v) => setForm({ ...form, imageUrl: v })} label="Portrait" /><Actions notice={notice} onCancel={editingId ? () => { setEditingId(null); setForm(emptyBoard); } : undefined} saving={create.isPending || update.isPending} label={editingId ? "Enregistrer" : "Ajouter le membre"} /></form></Panel><ContentList title="Membres enregistrés" loading={query.isLoading} empty="Aucun membre"><div className="space-y-3">{members.map((member) => <ListRow key={member.id} image={member.imageUrl} title={member.name} meta={`${member.role} · ${member.active ? "Visible" : "Masqué"}`} onEdit={() => { setEditingId(member.id); setForm({ name: member.name, role: member.role, bio: member.bio, imageUrl: member.imageUrl, sortOrder: String(member.sortOrder), active: member.active === 1 }); }} onDelete={() => window.confirm(`Supprimer « ${member.name} » ?`) && remove.mutate({ id: member.id })} />)}</div></ContentList></div></AdminSection>;
}

function AdminSection({ title, eyebrow, icon, stats, children }: { title: string; eyebrow: string; icon: React.ReactNode; stats?: React.ReactNode; children: React.ReactNode }) { return <><div className="flex items-end gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e6f0e9] text-[#075b36]">{icon}</span><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#009b3a]">{eyebrow}</p><h2 className="mt-1 text-3xl font-black tracking-[-0.05em]">{title}</h2></div></div>{stats && <div className="mt-6 grid gap-4 sm:grid-cols-3">{stats}</div>}<div className="mt-8">{children}</div></>; }
function AdminStat({ value, label, icon }: { value: number; label: string; icon: React.ReactNode }) { return <div className="rounded-[1.25rem] border border-[#e1e9e2] bg-white p-5 shadow-sm"><div className="flex size-10 items-center justify-center rounded-xl bg-[#e6f0e9] text-[#009b3a]">{icon}</div><p className="mt-4 text-3xl font-black text-[#075b36]">{value}</p><p className="mt-1 text-xs font-extrabold uppercase tracking-[0.12em] text-[#74877b]">{label}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="h-fit rounded-[1.5rem] border border-[#e1e9e2] bg-white p-6 shadow-sm sm:p-8"><h3 className="mb-6 text-2xl font-extrabold tracking-[-0.04em]">{title}</h3>{children}</section>; }
function ContentList({ title, loading, children }: { title: string; loading: boolean; empty?: string; children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-[#e1e9e2] bg-white p-6 shadow-sm sm:p-8"><h3 className="text-2xl font-extrabold tracking-[-0.04em]">{title}</h3>{loading ? <div className="mt-7 h-24 animate-pulse rounded-xl bg-[#f1f5f1]" /> : <div className="mt-7">{children}</div>}</section>; }
function ListRow({ image, title, meta, onEdit, onDelete }: { image: string; title: string; meta: string; onEdit: () => void; onDelete: () => void }) { return <article className="flex items-center gap-3 rounded-xl border border-[#edf1ed] p-3"><div className="size-16 shrink-0 overflow-hidden rounded-lg bg-[#e6f0e9]">{image && <img src={image} alt="" className="size-full object-cover" />}</div><div className="min-w-0 flex-1"><h4 className="truncate font-extrabold">{title}</h4><p className="mt-1 truncate text-xs text-[#74877b]">{meta}</p></div><button type="button" onClick={onEdit} className="rounded-full border border-[#cbd9ce] p-2 text-[#075b36]" aria-label={`Modifier ${title}`}><Pencil className="size-4" /></button><button type="button" onClick={onDelete} className="rounded-full border border-[#f1cccc] p-2 text-[#d62828]" aria-label={`Supprimer ${title}`}><Trash2 className="size-4" /></button></article>; }
function Field({ label, value, onChange, type = "text", placeholder, required }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string; required?: boolean }) { return <label className="block text-sm font-bold"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-[#587063]">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} required={required} className="h-11 w-full rounded-xl border border-[#dfe8e0] bg-white px-3.5 text-sm outline-none focus:border-[#009b3a] focus:ring-4 focus:ring-[#009b3a]/10" /></label>; }
function Actions({ notice, onCancel, saving, label }: { notice: string | null; onCancel?: () => void; saving: boolean; label: string }) { return <div className="space-y-3">{notice && <p className={`rounded-xl px-4 py-3 text-sm font-semibold ${notice.startsWith("Erreur") ? "bg-[#fff1f1] text-[#b42318]" : "bg-[#e6f0e9] text-[#075b36]"}`}>{notice}</p>}<div className="flex gap-3"><button type="submit" disabled={saving} className="inline-flex flex-1 items-center justify-center gap-2 rounded-full bg-[#075b36] px-5 py-3.5 text-sm font-extrabold text-white disabled:opacity-60">{saving ? "Enregistrement…" : <><Save className="size-4" />{label}</>}</button>{onCancel && <button type="button" onClick={onCancel} className="rounded-full border border-[#cbd9ce] px-4 text-sm font-bold text-[#075b36]"><X className="size-4" /></button>}</div></div>; }
