import { ArrowLeft, ArrowUpRight, Users } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function Board() {
  const query = trpc.board.list.useQuery();
  if (typeof document !== "undefined") document.title = "Bureau exécutif | Coordination des étudiants et stagiaires togolais au Maroc — Section Marrakech";
  const members = query.data ?? [];
  return <div className="min-h-screen bg-[#fbfcf9] text-[#17221c]"><header className="border-b border-white/20 bg-[#B15C01] pt-1 text-white"><div className="section-shell flex items-center justify-between py-5"><Link href="/" className="flex items-center gap-3"><span className="flex h-14 w-52 items-center justify-center sm:w-64"><img src="/assets/cestom-logo.webp" alt="Logo CESTOM" className="h-full w-full object-contain drop-shadow-[0_4px_8px_rgba(0,0,0,0.22)]" /></span><span className="hidden border-l border-white/30 pl-3 text-[10px] font-bold uppercase leading-4 tracking-[0.2em] text-white/85 sm:block">Coordination des étudiants<br />et stagiaires togolais au Maroc<br /><span className="text-[#f4c430]">Section Marrakech</span></span></Link><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-white/30 px-4 py-2.5 text-xs font-extrabold uppercase tracking-[0.1em] text-white transition-colors hover:bg-white/10"><ArrowLeft className="size-4" /> Accueil</Link></div></header><section className="bg-[#B15C01] py-20 text-white sm:py-28"><div className="section-shell"><p className="eyebrow eyebrow-light"><span className="eyebrow-dot bg-[#f4c430]" />Notre équipe</p><h1 className="display-heading mt-6 max-w-3xl text-5xl font-extrabold leading-[0.98] tracking-[-0.06em] sm:text-7xl">Le bureau exécutif.</h1><p className="mt-7 max-w-xl text-lg leading-7 text-white/70">Les membres qui coordonnent la vie et les engagements de la Coordination des étudiants et stagiaires togolais au Maroc — Section Marrakech.</p></div></section><main className="section-shell py-14 sm:py-20">{query.isLoading ? <p>Chargement…</p> : members.length === 0 ? <div className="rounded-3xl border border-dashed border-[#cbd9ce] px-6 py-20 text-center"><Users className="mx-auto size-9 text-[#B15C01]" /><h2 className="mt-4 text-2xl font-extrabold">Le bureau sera bientôt présenté</h2></div> : <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{members.map((member) => <article key={member.id} className="overflow-hidden rounded-[1.5rem] border border-[#e1e9e2] bg-white shadow-[0_12px_40px_rgba(20,68,42,0.05)]"><div className="aspect-square bg-[#e6f0e9]">{member.imageUrl ? <img src={member.imageUrl} alt={`Portrait de ${member.name}`} className="size-full object-cover" /> : <div className="flex size-full items-center justify-center text-6xl font-black text-[#B15C01]">{member.name.charAt(0)}</div>}</div><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#B15C01]">{member.role}</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.04em]">{member.name}</h2><p className="mt-4 text-sm leading-6 text-[#587063]">{member.bio}</p></div></article>)}</div>}<Link href="/actualites" className="mt-14 inline-flex items-center gap-2 text-sm font-extrabold uppercase tracking-[0.12em] text-[#B15C01]">Lire les actualités <ArrowUpRight className="size-4" /></Link></main></div>;
}
