import { ArrowLeft, ArrowUpRight, CalendarDays, Newspaper } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function News() {
  const query = trpc.news.list.useQuery();
  useEffectTitle("Actualités | Coordination des étudiants et stagiaires togolais au Maroc — Section Marrakech");
  const posts = query.data ?? [];
  return <div className="min-h-screen bg-[#fbfcf9] text-[#17221c]"><Header /><section className="bg-[#075b36] py-20 text-white sm:py-28"><div className="section-shell"><p className="eyebrow eyebrow-light"><span className="eyebrow-dot bg-[#f4c430]" />Vie de la communauté</p><h1 className="display-heading mt-6 max-w-3xl text-5xl font-extrabold leading-[0.98] tracking-[-0.06em] sm:text-7xl">Actualités et publications.</h1><p className="mt-7 max-w-xl text-lg leading-7 text-white/70">Les nouvelles, initiatives et temps forts de la Coordination des étudiants et stagiaires togolais au Maroc — Section Marrakech.</p></div></section><main className="section-shell py-14 sm:py-20">{query.isLoading ? <div className="grid gap-5 md:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-80 animate-pulse rounded-3xl bg-[#e8f0e9]" />)}</div> : posts.length === 0 ? <Empty /> : <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map((post) => <article key={post.id} className="overflow-hidden rounded-[1.5rem] border border-[#e1e9e2] bg-white shadow-[0_12px_40px_rgba(20,68,42,0.05)]"><div className="aspect-[1.5] bg-[#e6f0e9]">{post.imageUrl && <img src={post.imageUrl} alt="" className="size-full object-cover" />}</div><div className="p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#009b3a]">{post.category}</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.04em]">{post.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#587063]">{post.excerpt}</p><div className="mt-5 flex items-center justify-between border-t border-[#edf1ed] pt-4 text-xs text-[#74877b]"><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-3.5" />{formatDate(post.publishedAt)}</span><Link href={`/actualites/${post.id}`} className="inline-flex items-center gap-1 font-extrabold text-[#075b36]">Lire <ArrowUpRight className="size-3.5" /></Link></div></div></article>)}</div>}</main></div>;
}

function Header() { return <header className="border-b border-white/20 bg-[#075b36] pt-1 text-white"><div className="section-shell flex items-center justify-between py-5"><Link href="/" className="flex items-center gap-3"><span className="flex h-14 w-52 items-center justify-center sm:w-64"><img src="/assets/cestom-logo.webp" alt="Logo CESTOM" className="h-full w-full object-contain drop-shadow-[0_4px_8px_rgba(0,0,0,0.22)]" /></span><span className="hidden border-l border-white/30 pl-3 text-[10px] font-bold uppercase leading-4 tracking-[0.2em] text-white/85 sm:block">Coordination des étudiants<br />et stagiaires togolais au Maroc<br /><span className="text-[#f4c430]">Section Marrakech</span></span></Link><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-white/30 px-4 py-2.5 text-xs font-extrabold uppercase tracking-[0.1em] text-white transition-colors hover:bg-white/10"><ArrowLeft className="size-4" /> Accueil</Link></div></header>; }
function Empty() { return <div className="rounded-3xl border border-dashed border-[#cbd9ce] px-6 py-20 text-center"><Newspaper className="mx-auto size-9 text-[#009b3a]" /><h2 className="mt-4 text-2xl font-extrabold">Aucune publication pour le moment</h2><p className="mt-2 text-sm text-[#74877b]">Les prochaines nouvelles de la communauté apparaîtront ici.</p></div>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("fr-FR", { dateStyle: "long" }).format(date); }
function useEffectTitle(title: string) { if (typeof document !== "undefined") document.title = title; }
